#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset



if [ -z "${POSTGRES_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRES_USER="${base_postgres_image_default_user}"
fi

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

django_ready() {
  if curl -sSf ${DJANGO_ENDPOINT}/admin/ >/dev/null; then
    return 0
  else
    return -1
  fi
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

until django_ready; do
  >&2 echo 'Waiting for Django to become available...'
  sleep 3
done
>&2 echo 'ElasticSearch is available'

exec "$@"
